sudo: required
rvm:
  - 2.2.3
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database workshops_test;' -U postgres
addons:
  postgresql: '9.3'
